name: Dev
on:
  pull_request:
    branches:
      - master
jobs:
  publish:
    name: dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build iOS project
        run: dotnet build -c Release Omnicasa.Mobile.Maui.BlinkID.iOS/Omnicasa.Mobile.Maui.BlinkID.iOS.csproj
